# Generated by Django 3.1.5 on 2021-01-28 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theorytype', models.CharField(choices=[('LC', 'Comment about level'), ('TC', 'Comment about general technique')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorefile', models.FileField(unique=True, upload_to=scores.models.user_partition)),
                ('scoretype', models.CharField(choices=[('PI', 'Piece'), ('MS', 'Gamme mélodique'), ('HS', 'Gamme harmonique'), ('CS', 'Gamme en accords')], max_length=2)),
                ('scoretitle', models.CharField(max_length=100)),
                ('scorecollection', models.CharField(blank=True, max_length=100, null=True)),
                ('scoredate', models.DateTimeField(auto_now_add=True)),
                ('readlevel', models.PositiveIntegerField(default=1)),
                ('moderatorok', models.BooleanField(default=False)),
                ('mechanicalrights', models.BooleanField(default=False)),
                ('downloadOrWatch', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composerName', models.CharField(max_length=100)),
                ('composerOccupation', models.CharField(choices=[('CO', 'Composer'), ('TE', 'Teacher'), ('SC', 'Scene performer'), ('PS', 'Professionnal student'), ('YS', 'Young student'), ('AM', 'Music amateur'), ('AL', 'Algorythmic composer'), ('OT', 'Other')], max_length=2)),
                ('experience', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
