# Generated by Django 3.1.5 on 2021-01-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='composerOccupation',
            field=models.CharField(choices=[('CO', 'Compositeur'), ('TE', 'Enesignant'), ('SC', 'Musicien de scène'), ('PS', 'Etudiant professionnel'), ('YS', 'Jeune étudiant'), ('AM', 'Amateur de musique'), ('AL', 'Algorythme de composition'), ('OT', 'Autre')], max_length=2),
        ),
    ]
